# Generated by Django 3.2 on 2023-11-05 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_comment'),
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='product',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='products.product'),
            preserve_default=False,
        ),
    ]
