# Generated by Django 3.2 on 2023-11-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_comment'),
        ('testimonials', '0002_testimonial_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='products.product'),
        ),
    ]
